name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: smart_hunter_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres -d smart_hunter_test"
          --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        run: npm ci --legacy-peer-deps
      - name: Wait for Postgres
        run: sleep 5
      - name: Generate Prisma client & run migrations
        env:
          DATABASE_URL: postgresql://postgres:postgres@127.0.0.1:5432/smart_hunter_test
        run: |
          npx prisma generate
          npx prisma migrate deploy || true
      - name: Run tests
        env:
          DATABASE_URL: postgresql://postgres:postgres@127.0.0.1:5432/smart_hunter_test
        run: npm test -- --runInBand
